version: '3'
services:

  web:
    image: "psi/ideezer"
    build:
      context: .
      dockerfile: docker/Docker.web
    environment:
      DATABASE_URL: psql://ideezer:51fa5866c8ce751dda8048f1f092c65274637e40@db:5432/ideezer
      HOSTNAME: localhost
      SERVICE_NAME: web
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: "psi/ideezer-nginx"
    build:
      context: .
      dockerfile: docker/Docker.nginx
    ports:
      - 80:8000
    depends_on:
      - web

  db:
    image: postgres:11
    ports:  # FIXME for tesing only; remove for production
      - 5432:5432
    environment:
      POSTGRES_USER: ideezer
      POSTGRES_DB: ideezer
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
