# Generated by Django 2.0.7 on 2018-07-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeezerTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('deezer_id', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itunes_id', models.IntegerField(blank=True, null=True)),
                ('itunes_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deezer_id', models.IntegerField(blank=True, null=True)),
                ('deezer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('deezer_content', models.ManyToManyField(to='ideezer.DeezerTrack')),
            ],
        ),
        migrations.CreateModel(
            name='TrackIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.IntegerField()),
                ('choosen', models.NullBooleanField(default=None)),
                ('deezer_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideezer.DeezerTrack')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('itunes_id', models.IntegerField()),
                ('s_title', models.CharField(blank=True, max_length=255, null=True)),
                ('s_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('s_album', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trackidentity',
            name='user_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideezer.UserTrack'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='itunes_content',
            field=models.ManyToManyField(to='ideezer.UserTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrack',
            unique_together={('user', 'itunes_id')},
        ),
        migrations.AlterUniqueTogether(
            name='trackidentity',
            unique_together={('user_track', 'deezer_track', 'choosen')},
        ),
    ]
