# Generated by Django 2.0.7 on 2018-07-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='deezer_content',
            field=models.ManyToManyField(blank=True, to='ideezer.DeezerTrack'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='itunes_content',
            field=models.ManyToManyField(blank=True, to='ideezer.UserTrack'),
        ),
    ]
