# Generated by Django 2.1.4 on 2019-01-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0002_auto_20190106_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='itunes_persistent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='itunes_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
