# Generated by Django 2.1.4 on 2019-01-12 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0003_auto_20190106_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NS', 'not started'), ('ST', 'started'), ('FL', 'failed'), ('SC', 'success')], default='NS', max_length=2)),
                ('tracks_deleted', models.IntegerField()),
                ('playlists_deleted', models.IntegerField()),
                ('tracks_created', models.IntegerField()),
                ('playlists_created', models.IntegerField()),
                ('error', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
