# Generated by Django 2.0.7 on 2018-07-29 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideezer', '0003_playlist_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user', 'itunes_id')},
        ),
    ]
