# Generated by Django 2.1.4 on 2019-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0004_uploadhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='playlists_created',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='playlists_deleted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='tracks_created',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='tracks_deleted',
            field=models.IntegerField(null=True),
        ),
    ]
