# Generated by Django 2.1.4 on 2019-01-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0003_auto_20181106_1101'),
        ('ideezer', '0006_auto_20190112_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='error',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='task_id',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.TaskResult', unique=True),
            preserve_default=False,
        ),
    ]
