# Generated by Django 2.1.4 on 2019-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0009_auto_20190118_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrack',
            old_name='s_album',
            new_name='_s_album',
        ),
        migrations.RenameField(
            model_name='usertrack',
            old_name='s_artist',
            new_name='_s_artist',
        ),
        migrations.RenameField(
            model_name='usertrack',
            old_name='s_title',
            new_name='_s_title',
        ),
        migrations.AlterField(
            model_name='usertrack',
            name='_s_album',
            field=models.CharField(blank=True, db_column='s_album', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usertrack',
            name='_s_artist',
            field=models.CharField(blank=True, db_column='s_artist', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usertrack',
            name='_s_title',
            field=models.CharField(blank=True, db_column='s_title', max_length=255, null=True),
        ),
    ]
