# Generated by Django 2.1.5 on 2019-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0010_auto_20190120_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='itunes_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='itunes_persistent_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='itunes_title',
            field=models.CharField(max_length=255),
        ),
    ]
