# Generated by Django 2.1.5 on 2019-01-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0011_auto_20190126_1810'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackidentity',
            unique_together={('user_track', 'deezer_track'), ('user_track', 'choosen')},
        ),
    ]
