# Generated by Django 2.1.5 on 2019-02-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0014_remove_deezertrack_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deezertrack',
            name='deezer_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='deezer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='itunes_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='deezer_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertrack',
            name='itunes_id',
            field=models.BigIntegerField(),
        ),
    ]
