# Generated by Django 2.1.5 on 2019-02-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0015_auto_20190202_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackidentity',
            old_name='choosen',
            new_name='chosen',
        ),
        migrations.AlterUniqueTogether(
            name='trackidentity',
            unique_together={('user_track', 'chosen'), ('user_track', 'deezer_track')},
        ),
    ]
