# Generated by Django 2.1.5 on 2019-07-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideezer', '0016_auto_20190202_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['itunes_title']},
        ),
        migrations.AlterUniqueTogether(
            name='trackidentity',
            unique_together={('user_track', 'deezer_track')},
        ),
    ]
